/** Letter @ 96dpi (8.5in × 11in) */
export const TECHNICAL_SHEET_PAGE_WIDTH_PX = 816
export const TECHNICAL_SHEET_PAGE_HEIGHT_PX = 1056

/** Área útil de texto respecto al borde de la hoja (coincide con `.technical-sheet-content`). */
export const TECHNICAL_SHEET_CONTENT_TOP_PX = 125
export const TECHNICAL_SHEET_CONTENT_BOTTOM_PX = 105
export const TECHNICAL_SHEET_CONTENT_LEFT_PX = 105
export const TECHNICAL_SHEET_CONTENT_RIGHT_PX = 75

/** 1056 − 125 − 105 = 826 — altura máxima de bloques por página (paginación). */
export const TECHNICAL_SHEET_CONTENT_AVAILABLE_HEIGHT_PX =
  TECHNICAL_SHEET_PAGE_HEIGHT_PX - TECHNICAL_SHEET_CONTENT_TOP_PX - TECHNICAL_SHEET_CONTENT_BOTTOM_PX

/** 816 − 105 − 75 = 636 — ancho del flujo de texto (medición y caja de contenido). */
export const TECHNICAL_SHEET_CONTENT_INNER_WIDTH_PX =
  TECHNICAL_SHEET_PAGE_WIDTH_PX - TECHNICAL_SHEET_CONTENT_LEFT_PX - TECHNICAL_SHEET_CONTENT_RIGHT_PX

/** @deprecated Usar TECHNICAL_SHEET_CONTENT_AVAILABLE_HEIGHT_PX */
export const TECHNICAL_SHEET_SAFE_CONTENT_MAX_PX = TECHNICAL_SHEET_CONTENT_AVAILABLE_HEIGHT_PX
