import { beforeEach, describe, expect, it, vi } from "vitest"
import { fireEvent, render, screen, waitFor, within } from "@testing-library/react"
import { AdminVacancyCatalogContent } from "@/components/portal-admin/AdminVacancyCatalogContent"
import type { VacancyCatalogAdminItem } from "@/lib/api/admin-vacancy-catalogs"

const catalogApiMocks = vi.hoisted(() => ({
  listAdminVacancyCatalog: vi.fn(),
  getAdminVacancyCatalogItem: vi.fn(),
  createAdminVacancyCatalogItem: vi.fn(),
  updateAdminVacancyCatalogItem: vi.fn(),
  deleteAdminVacancyCatalogItem: vi.fn(),
}))

vi.mock("@/lib/api/admin-vacancy-catalogs", () => ({
  listAdminVacancyCatalog: catalogApiMocks.listAdminVacancyCatalog,
  getAdminVacancyCatalogItem: catalogApiMocks.getAdminVacancyCatalogItem,
  createAdminVacancyCatalogItem: catalogApiMocks.createAdminVacancyCatalogItem,
  updateAdminVacancyCatalogItem: catalogApiMocks.updateAdminVacancyCatalogItem,
  deleteAdminVacancyCatalogItem: catalogApiMocks.deleteAdminVacancyCatalogItem,
  sortVacancyCatalogItems: (items: VacancyCatalogAdminItem[]) =>
    [...items].sort((left, right) => left.sortOrder - right.sortOrder),
}))

function buildCatalogItem(
  overrides: Partial<VacancyCatalogAdminItem> = {}
): VacancyCatalogAdminItem {
  return {
    id: "dep-1",
    code: "engineering",
    displayName: "Engineering",
    description: "Equipo técnico",
    sortOrder: 1,
    isActive: true,
    vacanciesCount: 0,
    ...overrides,
  }
}

describe("AdminVacancyCatalogContent", () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it("renders the empty state for departments", async () => {
    catalogApiMocks.listAdminVacancyCatalog.mockResolvedValueOnce([])

    render(<AdminVacancyCatalogContent catalog="departments" />)

    expect(
      await screen.findByText("Aún no hay departamentos creados")
    ).toBeInTheDocument()
    expect(screen.getAllByRole("button", { name: /Crear departamento/i })).toHaveLength(2)
  })

  it("submits create with autogenerated code and reloads the list", async () => {
    const createdItem = buildCatalogItem({
      displayName: "Talento Humano",
      code: "talento-humano",
    })

    catalogApiMocks.listAdminVacancyCatalog
      .mockResolvedValueOnce([])
      .mockResolvedValueOnce([createdItem])
    catalogApiMocks.createAdminVacancyCatalogItem.mockResolvedValueOnce(createdItem)

    render(<AdminVacancyCatalogContent catalog="departments" />)

    await screen.findByText("Aún no hay departamentos creados")

    fireEvent.click(screen.getAllByRole("button", { name: /Crear departamento/i })[0])

    fireEvent.change(await screen.findByLabelText(/Nombre/i), {
      target: { value: "Talento Humano" },
    })

    expect(await screen.findByLabelText(/Código/i)).toHaveValue("talento-humano")

    fireEvent.click(screen.getByRole("button", { name: "Guardar" }))

    await waitFor(() => {
      expect(catalogApiMocks.createAdminVacancyCatalogItem).toHaveBeenCalledWith(
        "departments",
        expect.objectContaining({
          displayName: "Talento Humano",
          code: "talento-humano",
          sortOrder: 1,
          isActive: true,
        })
      )
    })

    expect(await screen.findByText("Talento Humano")).toBeInTheDocument()
  })

  it("shows the 409 conflict flow and offers deactivation", async () => {
    const inUseItem = buildCatalogItem({
      displayName: "Operaciones",
      code: "operaciones",
      vacanciesCount: 3,
    })

    catalogApiMocks.listAdminVacancyCatalog
      .mockResolvedValueOnce([inUseItem])
      .mockResolvedValueOnce([{ ...inUseItem, isActive: false }])
    catalogApiMocks.deleteAdminVacancyCatalogItem.mockRejectedValueOnce(
      Object.assign(new Error("No se puede eliminar porque está asociado a vacantes existentes."), {
        status: 409,
      })
    )
    catalogApiMocks.updateAdminVacancyCatalogItem.mockResolvedValueOnce({
      ...inUseItem,
      isActive: false,
    })

    render(<AdminVacancyCatalogContent catalog="departments" />)

    await screen.findByRole("button", { name: "Eliminar" })

    fireEvent.click(screen.getByRole("button", { name: "Eliminar" }))

    const deleteDialog = await screen.findByRole("dialog")
    fireEvent.click(within(deleteDialog).getByRole("button", { name: "Eliminar" }))

    expect(
      await screen.findByText(
        "No se puede eliminar porque está asociado a vacantes existentes."
      )
    ).toBeInTheDocument()

    fireEvent.click(
      screen.getByRole("button", { name: "Desactivar en su lugar" })
    )

    await waitFor(() => {
      expect(catalogApiMocks.updateAdminVacancyCatalogItem).toHaveBeenCalledWith(
        "departments",
        inUseItem.id,
        expect.objectContaining({
          isActive: false,
        })
      )
    })
  })
})
